type TypeChart = Record<
    string,
    {
        damageTo: Record<string, number>;
        damageFrom: Record<string, number>;
    }
>;

export const typeChart: TypeChart = {
    Normal: {
        damageTo: {
            Rock: 0.5,
            Ghost: 0,
            Steel: 0.5,
        },
        damageFrom: {
            Fighting: 2,
            Ghost: 0,
        },
    },
    Fire: {
        damageTo: {
            Fire: 0.5,
            Water: 0.5,
            Grass: 2,
            Ice: 2,
            Bug: 2,
            Rock: 0.5,
            Dragon: 0.5,
            Steel: 2,
        },
        damageFrom: {
            Fire: 0.5,
            Water: 2,
            Grass: 0.5,
            Ice: 0.5,
            Ground: 2,
            Bug: 0.5,
            Rock: 2,
            Steel: 0.5,
            Fairy: 0.5,
        },
    },
    Water: {
        damageTo: {
            Fire: 2,
            Water: 0.5,
            Grass: 0.5,
            Ground: 2,
            Rock: 2,
            Dragon: 0.5,
        },
        damageFrom: {
            Fire: 0.5,
            Water: 0.5,
            Electric: 2,
            Grass: 2,
            Ice: 0.5,
            Steel: 0.5,
        },
    },
    Electric: {
        damageTo: {
            Water: 2,
            Electric: 0.5,
            Grass: 0.5,
            Ground: 0,
            Flying: 2,
            Dragon: 0.5,
        },
        damageFrom: {
            Electric: 0.5,
            Ground: 2,
            Flying: 0.5,
            Steel: 0.5,
        },
    },
    Grass: {
        damageTo: {
            Fire: 0.5,
            Water: 2,
            Grass: 0.5,
            Poison: 0.5,
            Ground: 2,
            Flying: 0.5,
            Bug: 0.5,
            Rock: 2,
            Dragon: 0.5,
            Steel: 0.5,
        },
        damageFrom: {
            Fire: 2,
            Water: 0.5,
            Electric: 0.5,
            Grass: 0.5,
            Ice: 2,
            Poison: 2,
            Ground: 0.5,
            Flying: 2,
            Bug: 2,
        },
    },
    Ice: {
        damageTo: {
            Fire: 0.5,
            Water: 0.5,
            Grass: 2,
            Ice: 0.5,
            Ground: 2,
            Flying: 2,
            Dragon: 2,
            Steel: 0.5,
        },
        damageFrom: {
            Fire: 2,
            Ice: 0.5,
            Fighting: 2,
            Rock: 2,
            Steel: 2,
        },
    },
    Fighting: {
        damageTo: {
            Normal: 2,
            Ice: 2,
            Poison: 0.5,
            Flying: 0.5,
            Psychic: 0.5,
            Bug: 0.5,
            Rock: 2,
            Ghost: 0,
            Dark: 2,
            Steel: 2,
            Fairy: 0.5,
        },
        damageFrom: {
            Flying: 2,
            Psychic: 2,
            Bug: 0.5,
            Rock: 0.5,
            Dark: 0.5,
            Fairy: 2,
        },
    },
    Poison: {
        damageTo: {
            Grass: 2,
            Poison: 0.5,
            Ground: 0.5,
            Rock: 0.5,
            Ghost: 0.5,
            Steel: 0,
            Fairy: 2,
        },
        damageFrom: {
            Grass: 0.5,
            Fighting: 0.5,
            Poison: 0.5,
            Ground: 2,
            Psychic: 2,
            Bug: 0.5,
            Fairy: 0.5,
        },
    },
    Ground: {
        damageTo: {
            Fire: 2,
            Electric: 2,
            Grass: 0.5,
            Poison: 2,
            Flying: 0,
            Bug: 0.5,
            Rock: 2,
            Steel: 2,
        },
        damageFrom: {
            Water: 2,
            Electric: 0,
            Grass: 2,
            Ice: 2,
            Poison: 0.5,
            Rock: 0.5,
        },
    },
    Flying: {
        damageTo: {
            Electric: 0.5,
            Grass: 2,
            Fighting: 2,
            Bug: 2,
            Rock: 0.5,
            Steel: 0.5,
        },
        damageFrom: {
            Electric: 2,
            Grass: 0.5,
            Ice: 2,
            Fighting: 0.5,
            Ground: 0,
            Bug: 0.5,
            Rock: 2,
        },
    },
    Psychic: {
        damageTo: {
            Fighting: 2,
            Poison: 2,
            Psychic: 0.5,
            Dark: 0,
            Steel: 0.5,
        },
        damageFrom: {
            Fighting: 0.5,
            Psychic: 0.5,
            Bug: 2,
            Ghost: 2,
            Dark: 2,
        },
    },
    Bug: {
        damageTo: {
            Fire: 0.5,
            Grass: 2,
            Fighting: 0.5,
            Poison: 0.5,
            Flying: 0.5,
            Psychic: 2,
            Ghost: 0.5,
            Dark: 2,
            Steel: 0.5,
            Fairy: 0.5,
        },
        damageFrom: {
            Fire: 2,
            Grass: 0.5,
            Fighting: 0.5,
            Ground: 0.5,
            Flying: 2,
            Rock: 2,
        },
    },
    Rock: {
        damageTo: {
            Fire: 2,
            Ice: 2,
            Fighting: 0.5,
            Ground: 0.5,
            Flying: 2,
            Bug: 2,
            Steel: 0.5,
        },
        damageFrom: {
            Normal: 0.5,
            Fire: 0.5,
            Water: 2,
            Grass: 2,
            Fighting: 2,
            Poison: 0.5,
            Ground: 2,
            Flying: 0.5,
            Steel: 2,
        },
    },
    Ghost: {
        damageTo: {
            Normal: 0,
            Psychic: 2,
            Ghost: 2,
            Dark: 0.5,
        },
        damageFrom: {
            Normal: 0,
            Fighting: 0,
            Poison: 0.5,
            Bug: 0.5,
            Ghost: 2,
            Dark: 2,
        },
    },
    Dragon: {
        damageTo: {
            Dragon: 2,
            Steel: 0.5,
            Fairy: 0,
        },
        damageFrom: {
            Fire: 0.5,
            Water: 0.5,
            Electric: 0.5,
            Grass: 0.5,
            Ice: 2,
            Dragon: 2,
            Fairy: 2,
        },
    },
    Dark: {
        damageTo: {
            Fighting: 0.5,
            Psychic: 2,
            Ghost: 2,
            Dark: 0.5,
            Fairy: 0.5,
        },
        damageFrom: {
            Fighting: 2,
            Psychic: 0,
            Bug: 2,
            Ghost: 0.5,
            Dark: 0.5,
            Fairy: 2,
        },
    },
    Steel: {
        damageTo: {
            Fire: 0.5,
            Water: 0.5,
            Electric: 0.5,
            Ice: 2,
            Rock: 2,
            Steel: 0.5,
            Fairy: 2,
        },
        damageFrom: {
            Normal: 0.5,
            Fire: 2,
            Grass: 0.5,
            Ice: 0.5,
            Fighting: 2,
            Poison: 0,
            Ground: 2,
            Flying: 0.5,
            Psychic: 0.5,
            Bug: 0.5,
            Rock: 0.5,
            Dragon: 0.5,
            Steel: 0.5,
            Fairy: 0.5,
        },
    },
    Fairy: {
        damageTo: {
            Fire: 0.5,
            Fighting: 2,
            Poison: 0.5,
            Dragon: 2,
            Dark: 2,
            Steel: 0.5,
        },
        damageFrom: {
            Fighting: 0.5,
            Poison: 2,
            Bug: 0.5,
            Dragon: 0,
            Dark: 0.5,
            Steel: 2,
        },
    },
};
